tap "alajmo/mani"
tap "douglance/tap"
tap "f/mcptools"
tap "gabrie30/utils"
tap "ibigio/tap"
tap "jbreckmckye/formulae"
tap "keith/formulae"
tap "libsql/sqld"
tap "matheusml/zsh-git-ai"
tap "nanobot-ai/tap"
tap "nikitabobko/tap"
tap "onkernel/tap"
tap "pipedreamhq/pd-cli"
tap "simonw/llm"
tap "steipete/tap"
tap "supabase/tap"
tap "ttscoff/thelab"
tap "tursodatabase/tap"
tap "tw93/tap"
tap "vet-run/vet"
brew "age"
brew "xz"
brew "aspell"
brew "readline"
brew "bat"
brew "biome"
brew "caddy", restart_service: :changed
brew "fontconfig"
brew "carl"
brew "cloudflared"
brew "cmake"
brew "coreutils"
brew "csvlens"
brew "curl"
brew "dnsmasq", restart_service: :changed
brew "duckdb"
brew "duf"
brew "dug"
brew "duti"
brew "entr"
brew "eza"
brew "fd"
brew "fdupes"
brew "ffmpeg"
brew "fpc"
brew "fzf"
brew "gh"
brew "git"
brew "git-extras"
brew "git-xet"
brew "glow"
brew "gnupg"
brew "gum"
brew "gup"
brew "htmlq"
brew "httpie"
brew "libzip"
brew "imagemagick"
brew "jdupes"
brew "jj"
brew "jq"
brew "libyaml"
brew "ls-lint"
brew "mani"
brew "matcha"
brew "node"
brew "mcp-inspector"
brew "micro"
brew "moreutils"
brew "mprocs"
brew "mq"
brew "pandoc"
brew "pgloader"
brew "php"
brew "pnpm", link: false
brew "pocketbase"
brew "postgresql@17"
brew "rich-cli"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "shfmt"
brew "snitch"
brew "sops"
brew "speedtest-cli"
brew "sqlfmt"
brew "stormy"
brew "stow"
brew "sttr"
brew "svu"
brew "tokei"
brew "topgrade"
brew "tree"
brew "typst"
brew "wget"
brew "witr"
brew "xdg-ninja"
brew "xq"
brew "yq"
brew "yt-dlp"
brew "zns"
brew "douglance/tap/devsql"
brew "gabrie30/utils/ghorg"
brew "ibigio/tap/shell-ai"
brew "keith/formulae/reminders-cli"
brew "matheusml/zsh-git-ai/zsh-git-ai"
brew "nanobot-ai/tap/nanobot"
brew "onkernel/tap/kernel"
brew "pipedreamhq/pd-cli/pipedream"
brew "simonw/llm/ttok"
brew "steipete/tap/imsg"
brew "supabase/tap/supabase"
brew "ttscoff/thelab/gather-cli"
brew "tursodatabase/tap/turso"
brew "tw93/tap/mole"
brew "vet-run/vet/vet-run"
cask "1password"
cask "1password-cli"
cask "aerospace"
cask "appcleaner"
cask "arc"
cask "batfi"
cask "block-goose"
cask "bruno"
cask "cap"
cask "codexbar"
cask "coteditor"
cask "cursor"
cask "dataflare"
cask "discord"
cask "dropbox"
cask "flux-app"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-nerd-font"
cask "font-fontawesome"
cask "font-ia-writer-duo"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-linux-biolinum"
cask "font-linux-libertine"
cask "ghostty"
cask "github"
cask "google-chrome"
cask "google-drive"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "keyclu"
cask "leader-key"
cask "lm-studio"
cask "lookaway"
cask "mitmproxy"
cask "music-decoy"
cask "notion-calendar"
cask "numi"
cask "obsidian"
cask "pdf-expert"
cask "raycast"
cask "slack"
cask "tableplus"
cask "the-unarchiver"
cask "timing"
cask "visual-studio-code"
cask "vlc"
cask "wailbrew"

# NPM packages (install with: npm install -g <package>)
# 2025-12-06-create-cli
# 2025-12-06-create-rudolph
# ccusage
# cline
# corepack
# npm
# safe-rm
# sfw
# task-master-ai

# Rust packages (install with: cargo install <package>)
# cargo-cache
# cargo-update
# cfurl
# dotstate
# each
# git-graph
# hai-cli
# htmlq
# kanastra-palette-rs
# rink
# rmrfrs
# rustormy
# sleek
# swab
# toml2json
# uv-migrator
# worktrunk

# Bun packages (install with: bun install -g <package>)
# @assistant-ui/xpm
# @google/gemini-cli
# @google/jules
# @hono/cli
# @nbbaier/rudolph
# @openai/codex
# @pbnjs/cli
# @randomlabs/slatecli
# @sourcegraph/amp
# @steipete/bird
# @steipete/summarize
# @typescript/native-preview
# btca
# inngest-cli
# mdflow
# ocmt
# opencode-swarm-plugin
# pagedjs
# pagedjs-cli
# playwright
# puppeteer
# q-cli
# task-master-ai
# tsdown
# uipro-cli
# vercel
# vibe-rules
# vite
# vm-repack-2154
# wrangler

# UV packages (install with: uv tool install <package>)
# arcade-mcp
# basic-memory
# batrachian-toad
# cased-kit
# claude-code-transcripts
# claude-monitor
# elf
# files-to-prompt
# fs-explorer
# gitingest
# gradio
# huggingface-hub
# jupyterlab
# litecli
# llamactl
# llm
# markdown-plan
# mcp-scan
# md2term
# pgcli
# ruff
# shot-scraper
# sqlit-tui
# sqlite-utils
# strip-tags
