#!/bin/sh
duti -sv com.apple.dt.Xcode .plist editor
duti -sv com.apple.Music .m4a all
duti -sv com.apple.Music .mp3 all
duti -sv com.apple.QuickTimePlayerX .mov
duti -sv com.coteditor.CotEditor .txt editor
duti -sv com.microsoft.VSCode .astro editor
duti -sv com.microsoft.VSCode .bak editor
duti -sv com.microsoft.VSCode .bash editor
duti -sv com.microsoft.VSCode .bats editor
duti -sv com.microsoft.VSCode .bunch editor
duti -sv com.microsoft.VSCode .cfg editor
duti -sv com.microsoft.VSCode .cjs editor
duti -sv com.microsoft.VSCode .colors editor
duti -sv com.microsoft.VSCode .completion editor
duti -sv com.microsoft.VSCode .conf editor
duti -sv com.microsoft.VSCode .config editor
duti -sv com.microsoft.VSCode .css editor
duti -sv com.microsoft.VSCode .csv editor
duti -sv com.microsoft.VSCode .cts editor
duti -sv com.microsoft.VSCode .graphql editor
duti -sv com.microsoft.VSCode .grep editor
duti -sv com.microsoft.VSCode .ignore editor
duti -sv com.microsoft.VSCode .ini editor
duti -sv com.microsoft.VSCode .js editor
duti -sv com.microsoft.VSCode .json editor
duti -sv com.microsoft.VSCode .jsonc editor
duti -sv com.microsoft.VSCode .jsx editor
duti -sv com.microsoft.VSCode .log editor
duti -sv com.microsoft.VSCode .lua editor
duti -sv com.microsoft.VSCode .map editor
duti -sv com.microsoft.VSCode .md editor
duti -sv com.microsoft.VSCode .mdx editor
duti -sv com.microsoft.VSCode .mjs editor
duti -sv com.microsoft.VSCode .mts editor
duti -sv com.microsoft.VSCode .opml editor
duti -sv com.microsoft.VSCode .sh editor
duti -sv com.microsoft.VSCode .svelte editor
duti -sv com.microsoft.VSCode .svg editor
duti -sv com.microsoft.VSCode .toml editor
duti -sv com.microsoft.VSCode .ts editor
duti -sv com.microsoft.VSCode .tsv editor
duti -sv com.microsoft.VSCode .tsx editor
duti -sv com.microsoft.VSCode .vue editor
duti -sv com.microsoft.VSCode .xml editor
duti -sv com.microsoft.VSCode .yaml editor
duti -sv com.microsoft.VSCode .yml editor
duti -sv com.microsoft.VSCode .zsh editor
duti -sv org.videolan.vlc .3gp all
duti -sv org.videolan.vlc .aac all
duti -sv org.videolan.vlc .aif all
duti -sv org.videolan.vlc .avi all
duti -sv org.videolan.vlc .flac all
duti -sv org.videolan.vlc .flv all
duti -sv org.videolan.vlc .iff all
duti -sv org.videolan.vlc .m4a all
duti -sv org.videolan.vlc .m4v all
duti -sv org.videolan.vlc .mid all
duti -sv org.videolan.vlc .mkv all
duti -sv org.videolan.vlc .mp4 all
duti -sv org.videolan.vlc .mpa all
duti -sv org.videolan.vlc .mpeg all
duti -sv org.videolan.vlc .mpg all
duti -sv org.videolan.vlc .mpg4 all
duti -sv org.videolan.vlc .ogg all
duti -sv org.videolan.vlc .ra all
duti -sv org.videolan.vlc .wav all
duti -sv org.videolan.vlc .webm all
duti -sv org.videolan.vlc .wma all
duti -sv org.videolan.vlc .wmv all
